### ISSUE TITLE
Implementation of new DHCR IMAP mailadress

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#42]
The current "CC" email address can only accesed by Anna. The new one can be accessed by the whole team.

**Comment by patrickakk** [comment]
The new emailaddress is: dh-course-registry@dhcr.clarin-dariah.eu
This should replace dh-course-registry@oeaw.ac.at which is currently used as sender (from) for emails sent by the application as well it's put on CC of some mails to provide a basic "logging".

**Comment by patrickakk** [comment]
@IvdL22  @PixlTracer 
Can we define first what we are going to use this email address for?

Current situation:
The current email address dh-course-registry@oeaw.ac.at is **not** an IMAP account, and can only be accessed by Anna.

There are two situations, in case the application sends mail to a user:
1. a CC of some mails is sent to this email address.
2. there is an email adress listed as sender (FROM).

Proposed solution:
The new email address dh-course-registry@dhcr.clarin-dariah.eu is an IMAP account which means the mail is stored there (no forwarding). And it can be accessed by everyone in the team.

I would suggest to use the new email address only for the CC's which the application is sending.

As sender (from field) we can use the new helpdesk@ emailadress, from this issue:
https://github.com/acdh-oeaw/dhcr-main/issues/56

This way there will be one place for all mails send by users. And a separate place for the CC's from the application.

Are there any questions or can we agree on this solution?

**Comment by dietervu** [comment]
The address (imap account) we created is dhcr /at/ clarin-dariah.eu

@IvdL22 can access the password via bitwarden and share it with the others. Config details at https://www.transip.eu/knowledgebase/entry/309-the-email-settings-at-transip/ or you can access the roundcube mail interface via https://transip.email

**Comment by IvdL22** [comment]
@dietervu Thank you very much. I will test this and look for the password. We will use dhcr /at/ clarin-dariah.eu to send automatic notifications to the course creators when their course expires. Would it be possible that you to create another email **helpdesk@clarin-dariah.eu** so that we can put this on the website for the users to contact us when they have questions? 
cc @PixlTracer @vronk

**Comment by patrickakk** [comment]
@IvdL22 

What do you mean with:

> We will use dhcr /at/ clarin-dariah.eu to send automatic notifications to the course creators when their course expires. 

Currently the course reminders are the only emails which are logged in a decent way (=logged in the DB and available though the admin panel)! So why do you mention them for using a CC email address? Other parts of the application (legacy) are "logged" by sending a CC.

> Would it be possible that you to create another email [helpdesk@clarin-dariah.eu](mailto:helpdesk@clarin-dariah.eu)

Can we put that on hold, until we discussed that  the following issue:
https://github.com/acdh-oeaw/dhcr-main/issues/56

Please discuss there the exact email address as well as the purpose and who is going tho maintain this.

Thanks.

And can you let me know if you agree with the proposed solution above?

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 

REMINDER:

Can both of you please indicate if the proposed solution above is what we are looking for?

Especially:

> I would suggest to use the new email address only for the CC's which the application is sending.

**Comment by IvdL22** [comment]
Hi @patrickakk As far as @PixlTracer and I are concerned #56 has been discussed and decided.

(mailto:dhcr@clarin-dariah.eu) - cc’s mails sent by the system (eg course expires, system notifies lecturer, this address is in cc) & newsletter

(mailto:helpdesk@clarin-dariah.eu) - contact email for the users to reach out to; 
list this address in the contact section on the website to replace the personal addresses.

Please let me know if there is something that I do not understand from a technical point of view.

**Comment by patrickakk** [comment]
@IvdL22 

Thanks for your quick reponse. Nice that we are all on the same page about this email address.

Can we define the details for the "helpdesk" email address in the corresponding issue? Here: https://github.com/acdh-oeaw/dhcr-main/issues/56

Note:
-There are no CC mails for logging purposes sent for the course reminders/course expire. They are logged in the database and available in the admin area.

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 

Here's my prososal for the migration and phase out plan

**Summary**
The existing email account which is only accessible by one team member will be replaced by two new email accounts which can be accessed by everyone. One account will be for the email CC's sent by the application (simple logging), the other one will be a "helpdesk" email address where users can ask their questions.

**Migration plan**
- [x] M.1 Finish the definitions for the "helpdesk" email address, here: https://github.com/acdh-oeaw/dhcr-main/issues/56#issuecomment-1427794652
- [x] M.2 Create helpdesk email imap account
- [x] M.3 Remove personal email adresses of admins and replace by helpdesk email address on contact page
- [x] M.4 Set helpdesk email address as reply to and from for all mails sent by application
- [x] M.5 Change CC email address in the application


**Phase out plan**
- [x] P.1 Set a start date. (when the migration is finished)
- [ ] P.2 In the first 3 months Anna checks once a month if email is coming in at the old oaew email address. If mails come in, additional communication and actions might be needed. If no mail comes in, everything is ok.
- [ ] P.3 After 3 months there is no need to do a monthly check for new mails on the old account. The old accounts remains another 3 months for archive purposes.
- [ ] P.4 After 6 months an "archive" of 6 months logging has been build up in the new account. The old account with all containing emails can be completely removed by the sysadmin


Are there any questions, suggestions, or can we all agree on this?

**Comment by PixlTracer** [comment]
hi Patrick, 
thank you for streamlining the migration and phase out plan!
let's discuss this email address jungle in tomorrow's JFX to make sure we are all on the same page in terms of name & purpose -- I have accumulated several tentative addresses in the agenda.
once this is sorted I am optimistic that we can find a decision (ideally already in the next meeting)

**Comment by vronk** [comment]
M.5 cc: dhcr@clarin-dariah.eu

**Comment by vronk** [comment]
in the end there are two addresses:
cc for internal messages: dhcr@clarin-dariah.eu
official helpdesk address: dhcr-helpdesk@clarin-dariah.eu

**Comment by vronk** [comment]
from: no-reply@dhcr.clarin-dariah.eu
reply-to: dhcr-helpdesk@clarin-dariah.eu

**Comment by patrickakk** [comment]
@PixlTracer  @IvdL22 
For task M.3:
Can you provide the new text with explanation for the contact us section, found here:
https://dhcr.clarin-dariah.eu/info#contact

**Comment by IvdL22** [comment]
@patrickakk @PixlTracer Please see the suggestion below. OK?

**OLD TEXT**
For technical questions or yet not moderated countries, please seek contact to the administration board.

Before you contact us, please check the [FAQ page](https://dhcr.clarin-dariah.eu/faq/public) to see if your enquiry has already been answered.

**NEW TEXT**
If you have any technical questions about the DH course registry, please check the [FAQ page] or contact us here: [dhcr-helpdesk@clarin-dariah.eu](mailto:dhcr-helpdesk@clarin-dariah.eu)

**Comment by patrickakk** [comment]
@IvdL22 Thanks. Now we need to wait for @PixlTracer to check it additional changes are needed?

I'll also update the link for the bug report button, so that it links to creating an issue on this GitHub repo.

**Comment by PixlTracer** [comment]
I am ok with the proposed suggestions/text, thank you!

**Comment by patrickakk** [comment]
**Task M.3: development finished**
The explanations are updated here:
https://test-dhcr.clarin-dariah.eu/info#contact
and
https://test-dhcr.clarin-dariah.eu/national-moderators

this can be only be reviewed after the current version (2023-02) is released. until then it won't be visible.

currently blocked

**Comment by patrickakk** [comment]
**Task M.5 Change CC email address in the application**
For all instances changed to: dhcr /at/ clarin-dariah.eu

**Comment by patrickakk** [comment]
**Task  M.4 Set helpdesk email address as reply to and from for all mails sent by application**

Set reply to emailaddress for all instances: dhcr-helpdesk /at/ clarin-dariah.eu

Set from emailaddress for production to no-reply /at/ dhcr.clarin-dariah.eu

**Comment by patrickakk** [comment]
@IvdL22  @PixlTracer Can you review this?

Task M.3: Remove personal email adresses of admins and replace by helpdesk email address on contact page
The explanations are updated here:
https://test-dhcr.clarin-dariah.eu/info#contact
and
https://test-dhcr.clarin-dariah.eu/national-moderators

Since there are more subtasks in this issue, there is no need to change the label to done. You could just write a comment ;)

**Comment by PixlTracer** [comment]
looks fine, well done!

**Comment by patrickakk** [comment]
Task M.3: Implemented in 2023-03. Now waiting for review.

**Comment by PixlTracer** [comment]
looks fine!
one minor thing: currently, in test (https://test-dhcr.clarin-dariah.eu/info#contact) bug reporting is re-directing the user to Hendrick's git (https://github.com/hashmich/DHCR-Front-End/issues) --> use this url instead?
https://github.com/acdh-oeaw/dhcr-main/issues/new 

besides that i have nothing to add; I'll assign the label 'done'

**Comment by patrickakk** [comment]
Removed the Done label, to keep the Issue open for the tasks of the Phase out plan.

Moved to Mai milestone, to keep this Issue in focus for those tasks.

@PixlTracer Thanks for the review and the feedback. Updating the Bug report button and description is addressed and the latest status can be found in this issue: https://github.com/acdh-oeaw/dhcr-main/issues/41#issuecomment-1519041024

**Comment by patrickakk** [comment]
Task: P.1 Set a start date
This will be today: **2023-04-25** since all the changes to the UI and application logic are online since today.

**Comment by patrickakk** [comment]
@PixlTracer can you take care of the following, and write a line here monthly with the results?

Task:  P.2 In the first 3 months Anna checks once a month if email is coming in at the old oaew email address. If mails come in, additional communication and actions might be needed. If no mail comes in, everything is ok.

**Comment by patrickakk** [comment]
Blocked until 2023-10-25.

Until then Anna will check if emails are received at the old oeaw address.

After this date the old address and all data can be removed (see phase out plan above).

**Comment by PixlTracer** [comment]
I have checked dh-course-registry /at/ oeaw.ac.at today;
the last emails are from end of March 2023; since then no new emails are entering the inbox

**Comment by patrickakk** [comment]
@PixlTracer Thanks for the update. It sounds like everything works as it's supposed to ;)

**Comment by PixlTracer** [comment]
checked again today - no new emails :)

**Comment by patrickakk** [comment]
Thanks for the update.

**Comment by patrickakk** [comment]
Move to November milestone, since the next step (except for checking for new mails once), should be taken in October.

**Comment by patrickakk** [comment]
Waiting for confirmation of removing the account dh-course-registry@oeaw.ac.at

**Comment by patrickakk** [comment]
Status: Discussed in meeting at 2024-01-24. Waiting for response.

**Comment by patrickakk** [comment]
@vronk 

Can we close this issue?

Latest status here:
https://github.com/acdh-oeaw/dhcr-main/issues/42#issuecomment-1812690776

**Comment by vronk** [comment]
account was removed
