### ISSUE TITLE
Clean up users with 2 email addresses

### ISSUE THREAD

**Issue by vronk** [acdh-oeaw/dhcr-main#50]
- [x] 1. Clean up admins who have not logged in for 1 year
- [x] 2. Clean up old invitations
- [ ] 3. Clean up users with 2 email addresses

**Comment by patrickakk** [comment]
@IvdL22  @PixlTracer 
Task 1:
Currently there are 7 users with admin rights. From those 2 users didn't login within the last year.

Can their admin rights be removed, or do we want to communicate something first?

Task 2:
Currently there are 67 pending invitations. Of those 64 expired more than 1 year ago. Can you confirm that those can be deleted? This is a permanent action and can not be reverted/undone.

Task 3:
After finishing task 1 and 2, we can start with task 3.

**Comment by patrickakk** [comment]
@PixlTracer @IvdL22

REMINDER:

Would it be possible to  answer the questions at task 1 & 2?

**Comment by IvdL22** [comment]
@patrickakk @PixlTracer 

Task 1:
Patrick, Who are the 2 users? Please let us know by email.

Task 2: I think you can remove the pending invitations older than 1 year.

**Comment by patrickakk** [comment]
@IvdL22 
Task 1:
It's not --- . Maybe we should put it on the agenda for the next meeting, to avoid discussing personal data here?

**Comment by IvdL22** [comment]
@patrickakk See the updated comment, no need to wait until the next meeting.

**Comment by patrickakk** [comment]
Task 1 finished.

**Comment by patrickakk** [comment]
@IvdL22 Do we need to wait for a response from @PixlTracer for task 2? Or can I proceed as you confirmed?

**Comment by IvdL22** [comment]
@IvdL22 I think you can safely proceed, Patrick, thank you very much.

**Comment by patrickakk** [comment]
Task 2 finished.

**Comment by patrickakk** [comment]
Moved to Mai milestone, to give a realistic estimation of finishing task 3.

**Comment by patrickakk** [comment]
@PixlTracer @IvdL22
**Task 3: Users with multiple accounts**
The list is available. There is a total of 55 duplicate accounts. I'll send the list per mail.

Can you check the list and come up with suggestions how we want to deal with this?

**Comment by PixlTracer** [comment]
okay, please send over the list;
since we encourage users to register with their institutional email address (keeping in mind the federated login in the future), I'd propose to contact them individually.

**Comment by patrickakk** [comment]
@PixlTracer 
(cc @IvdL22 )

You already received the list per mail ;) On 2023-06-12 at 15:24 hours.

Do you want me to send the email again?

**Comment by patrickakk** [comment]
Moved to July milestone, because this will probably not be finished in May ;)

The list for task 3 is present and we can talk about this in a meeting when everybody is present.

**Comment by PixlTracer** [comment]
-- new list in .xlsm format requested - pending

**Comment by patrickakk** [comment]
New list in XLSX format send.

(I would recommend not to use XLSM if not explicitly needed)

**Comment by PixlTracer** [comment]
sent an email with my two cents on this topic
"DHCR - Users with multiple accounts"

**Comment by patrickakk** [comment]
@PixlTracer  I've replied

@IvdL22 Looking forward to your opinion about this.

**Comment by patrickakk** [comment]
Briefly addressed in the meeting of 13th September. It's work in progress.

Moved to September milestone, so older milestones can be closed.

**Comment by vronk** [comment]
Let's try to clean up ourselves based on heuristics:
the latest account, and/or the one with courses
