### ISSUE TITLE
Empty descriptions - meta data quality

### ISSUE THREAD

**Issue by patrickakk** [acdh-oeaw/dhcr-main#74]
@PixlTracer  @IvdL22 @vronk 

As discussed in the meeting today:

- [x] Provide a list of all courses with empty descriptions (Patrick)
- [x] This will be discussed during the WG meeting, how moderators can contribute to fix this. (Anna & Iulliana)
- [x] Do now allow empty descriptions. Validation in model and DB (Patrick)

**Comment by patrickakk** [comment]
@PixlTracer @vronk @IvdL22 

Today I took a look at the production database and found 90 courses with an empty description. Those courses are all archived and not public shown. 
So there won't be a list to discuss at the WG meeting?
For now we don't need to take an action on this?

The example I mentioned of a course with empty description happened at the end of last year and has been fixed by now.

Please understand that I don't look at every course separately.  So I only see things when testing a new feature. In that case, of course, I can mention this.

So the good news is that, in the active/public shown courses, we currently don't have this problem.

I have changed the model, so that the field description will be required in release 2023-05.
This can be tested here:
https://dev-dhcr.clarin-dariah.eu/courses/add

It is not changed in the database, since this is not possible because of the old courses without description.

Can you review this and change the label to done, when you agree that no further actions are needed?

**Comment by IvdL22** [comment]
Thank you @patrickakk (cc @PixlTracer ). This is fine now. Would it be possible to extend a bit the suggestion of the text in grey "Please provide the course descriptions in English."

Some participants of our second workshop yesterday at DARIAH2023 asked to encourage course, contributors, to also include the learning outcomes in the course descriptions. Hence, I would like to suggest the following text:

"Please add in English the general aims of the course/programme and the learning outcomes."

Ok to include this request in here or do you want me to open a new issue?
thank you

**Comment by patrickakk** [comment]
@IvdL22 (cc @PixlTracer ) It's fine to add it here. The change has been implemented in 2023-05. You can check it here:
https://dev-dhcr.clarin-dariah.eu/courses/add

Note: This text is only shown when the field description is empty, so when adding a new course. If you want a message which is also shown when the course is updated/edited, it could be done like the line below ECTS.

Can you change the label to "Done" when you're satisfied and this issue can be closed?

**Comment by PixlTracer** [comment]
Hi all, 
checked the Description Field in dev (screenshot) and it seems that the additional sentence proposed by Iulianna has not been implemented (yet?)
@patrickakk can you change the text in the description field from "Please provide the course description in English" to 
"Please provide the course description in English, as well as the general aims of the course/programme and the learning outcomes."
thanks!
![Bildschirmfoto 2023-06-13 um 14 43 04](https://github.com/acdh-oeaw/dhcr-main/assets/117655705/44ac17a0-d40c-4eff-816c-ccde14a951b8)

**Comment by patrickakk** [comment]
@PixlTracer Did you check the link, specified in the comment above ?  (https://github.com/acdh-oeaw/dhcr-main/issues/74#issuecomment-1582324053)
(cc @IvdL22 )

The text -as specified by Iulliana- is there ? See screenshot:
![image](https://github.com/acdh-oeaw/dhcr-main/assets/97846194/febefc9b-6006-4cce-8108-9737e42a7c71)


Can you change the label to "Done" when you're satisfied and this issue can be closed?

**Comment by IvdL22** [comment]
@patrickakk Done, thanks!

**Comment by patrickakk** [comment]
The change above is implemented in 2023-05.

**Comment by patrickakk** [comment]
When using another approach, it seems like there are still a lot of courses with empty descriptions.

I'll check that and get back on it.

**Comment by patrickakk** [comment]
Moved to November milestone, since we're still not finished with cleaning up duplicate user accounts. (See #50).

And too much "lists" might be confusing.

**Comment by patrickakk** [comment]
@IvdL22  @PixlTracer 

Just for info:
Now I've checked this again. The empty descriptions were probably only from older/not visible courses.  From the currently public visible courses, almost all have descriptions available.

Probably also because of:

> I have changed the model, so that the field description will be required in release 2023-05.

So it seems that everything is solved and the issue can be closed (again).
